FinalAgain/Models/Fooorm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FinalAgain.Models
{
    public class Fooorm
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        [MaxLength(45)]
        public string Header { get; set; }
        [MaxLength(245)]
        public string Text { get; set; }

        public int ViewCount { get; set; }
        public int AnswerCount { get; set; }
        public DateTime CreatedAt { get; set; }
        public List<FooormAnswers> FooormAnswers { get; set; } = new List<FooormAnswers>();
        public AppUser User { get; set; }

    }
}

FinalAgain/Controllers/FooormController.cs
using FinalAgain.DAL;
using FinalAgain.Models;
using FinalAgain.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;

namespace FinalAgain.Controllers
{
    public class FooormController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly AppDBContext _context;

        public FooormController(AppDBContext context , UserManager<AppUser> userManager)
        {
            _userManager = userManager;
            _context = context;
        }
        public IActionResult Index()
        {
            var data = _context.Fooorms.OrderByDescending(x => x.ViewCount).Take(10).ToList();
            return View(data);
        }
        public IActionResult CreateFooorm()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateFooorm(Fooorm form)
        {
            if (ModelState.IsValid)
            {
                var user = _userManager.FindByNameAsync(User.Identity.Name).Result;
                form.CreatedAt = DateTime.Now;
                form.User = user;
                form.UserId = user.Id;
                _context.Fooorms.Add(form);
                _context.SaveChanges();
                return RedirectToAction("index");
            }
            else
            {
                return View();
            }
        }
        public IActionResult ShowFooormItem([FromBody] int id)
        {
            var data = _context.Fooorms.FirstOrDefault(x => x.Id == id);
            data.ViewCount += 1;
            _context.SaveChanges();
            return Ok(data);
        }
        public IActionResult ShowFroomAnswers([FromBody] int id)
        {
            var answers = _context.FooormAnswers.Include(x=>x.User).Where(x=>x.FooormId==id).ToList();
            return Ok(answers);
        }
        public IActionResult SetMessage([FromBody] FooormAnswers answer)
        {
            AppUser user = _userManager.FindByNameAsync(User.Identity.Name).Result;
            var fooorm = _context.Fooorms.FirstOrDefault(x => x.Id == answer.FooormId);
            fooorm.AnswerCount += 1;
            answer.User = user;
            answer.UserId = user.Id;
            answer.Fooorm = fooorm;
            answer.CreatedAt = DateTime.Now;
            _context.FooormAnswers.Add(answer);
            _context.SaveChanges();
            return Ok();
        }
        public IActionResult SortTopQuestions()
        {
            var data=_context.Fooorms.OrderByDescending(x => x.ViewCount).Take(10).ToList();
            return Ok(data);
        }
        public IActionResult SortLatestQuestions()
        {
            var data = _context.Fooorms.OrderByDescending(x => x.CreatedAt).Take(10).ToList();
            return Ok(data);
        }
        public IActionResult SetUsefulMessage([FromBody] UserfulMessageViewModel model)
        {
            var user = _userManager.FindByNameAsync(User.Identity.Name).Result;
            if (user.Id == model.UserId)
            {
                var question = _context.FooormAnswers.FirstOrDefault(x => x.Id == model.TextId);
                if (question.IsUseful == false)
                {
                    question.IsUseful = true;
                    _context.SaveChanges();
                    return Ok(true);
                }
                question.IsUseful = false;
                _context.SaveChanges();
                return Ok(true);
            }
            return Ok(false);
        }
        public IActionResult SearchFooorm([FromBody] string value)
        {
            var data = _context.Fooorms.Where(x => x.Header.Contains(value)).ToList();
            return Ok(data);
        }
    }
}

FinalAgain/Views/Fooorm/CreateFooorm.cshtml
@model Fooorm
<div class="main">
    <nav class="navbar navbar-expand navbar-light navbar-bg justify-content-between">
        <a class="sidebar-toggle js-sidebar-toggle hamburgerA">
            <img src="~/assets/images/Hamburger.png">
        </a>
    </nav>
    <div class="MainSection">
        <div class="container">
            <div class="row">
                <div class="col-12 Profile mt-3">
                    <div class="col-12 mt-3 ms-1">
                        <h1>Ask New Question</h1>
                    </div>
                    <div class="col-12">
                        <form class="d-flex flex-column" asp-action="CreateFooorm" method="post">
                            <input asp-for="Header" placeholder="Title" class="fooormInput">
                            <span asp-validation-for="Header" class="text-white validationFooorm">Max 50 char</span>
                            <textarea asp-for="Text" placeholder="Body" cols="5" rows="12" class="fooormTextArea">

                            </textarea>
                            <span asp-validation-for="Text" class="text-white validationFooorm">Max 245 char</span>
                            <button type="submit" class="fooormSubmit ">ASK</button>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
@section scripts{
    <script src="~/assets/js/app.js"></script>
		}

FinalAgain/Views/Fooorm/Index.cshtml
@model List<Fooorm>
<div class="main">
    <nav class="navbar navbar-expand navbar-light navbar-bg justify-content-between">
        <a class="sidebar-toggle js-sidebar-toggle hamburgerA">
            <img src="/assets/images/Hamburger.png">
        </a>
        <ul class="inboxButtons">
            <li>
                <a class="userList-toggle">
                    <i class="fa-solid fa-align-center"></i>
                </a>
            </li>
        </ul>
    </nav>
    <main>
        <div class="main d-flex flex-row">
            <div class="inboxUserList text-center" id="UL">
                <ul class="newHeadersList d-flex flex-column">
                    <li class="askQuestion align-items-center pt-2">
                        <div>
                            <a asp-action="CreateFooorm">
                                <i class="fa-solid fa-circle-plus"></i>
                                <p>
                                    Ask a new Questiooon
                                </p>
                            </a>
                        </div>
                    </li>
                    <li class="SearchFooorm align-items-center pt-2">
                        <div>
                            <input class="mb-2 d-block mx-auto searchInput"/>
                            <a class="searchButton searchFooorm" asp-action="SearchFooorm" asp-controller="Fooorm"><i class="fa-brands fa-searchengin" style="font-size:20px;"></i> Search Question</a>
                        </div>
                    </li>
                    <li class="fooormHr1">
                        <hr class="fooormHr">
                    </li>
                    <li>
                        <a class="fooormBTN btn btn-link" asp-action="SortTopQuestions"><span>Top 10</span> Questions</a>
                    </li>
                    <li>
                        <a class="fooormBTN btn" asp-action="SortLatestQuestions"><span>Latest</span> Questions</a>
                    </li>
                    <li class="fooormHr1">
                        <hr class="fooormHr">
                    </li>
                    @*===========================================*@
                    @foreach (Fooorm fooorm in Model)
                    {
                        <li class="fooormList">
                            <a asp-action="ShowFooormItem" class="fooormListA" id="@fooorm.Id">
                                <div class="header">
                                    <p>@fooorm.Header</p>
                                </div>
                                <div class="info text-start">
                                    <p> @fooorm.AnswerCount answer </p>
                                    <p> @fooorm.ViewCount view </p>
                                </div>
                            </a>
                        </li>
                    }
                   
                </ul>
            </div>
            <div class="chatSection d-flex flex-column justify-content-between ">
                <div class="container">
                    <div class="row text-center headerHTML">
                        
                    </div>
                    <div class="row">
                        <ul class="answerList">
                            
                        </ul>
                    </div>
                </div>
                <div class="textArea text-center d-flex flex-column justify-content-between ">
                    <div class="container">
                        <div class="row">
                        </div>
                    </div>
                    <div class="fooormInputDiv displayN">
                        <input type="text" class="fooormInput" >
                        <button id="sendButton" asp-action="SetMessage" asp-controller="Fooorm"><img src="~/assets/images/FrogJump.png"/></button>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>
@section scripts{
    <script src="~/assets/js/app.js"></script>
    <script src="~/assets/js/ShowFooorm.js"></script>
    <script src="~/assets/js/MessageSendFooorm.js"></script>
    <script src="~/assets/js/SortFooorm.js"></script>
    <script src="~/assets/js/FooormSearch.js"></script>
	}	